#
# Copyright 2018-2019 Smithsonian Institution.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.You may obtain a copy of
# the License at: http://www.apache.org/licenses/
#
# This software and accompanying documentation is supplied without
# warranty of any kind. The copyright holder and the Smithsonian Institution:
# (1) expressly disclaim any warranties, express or implied, including but not
# limited to any implied warranties of merchantability, fitness for a
# particular purpose, title or non-infringement; (2) do not assume any legal
# liability or responsibility for the accuracy, completeness, or usefulness of
# the software; (3) do not represent that use of the software would not
# infringe privately owned rights; (4) do not warrant that the software
# is error-free or will be maintained, supported, updated or enhanced;
# (5) will not be liable for any indirect, incidental, consequential special
# or punitive damages of any kind or nature, including but not limited to lost
# profits or loss of data, on any basis arising from contract, tort or
# otherwise, even if any of the parties has been warned of the possibility of
# such loss or damage.
#
# This distribution includes several third-party libraries, each with their own
# license terms. For a complete copy of all copyright and license terms, including
# those of third-party libraries, please see the product release notes.
#

########################################################
# enables test rest endpoints with default values and
# sets up static hosted files used for testing
#
# static files for testing should be placed in:
# ${user.dir}/test-classes/sample-data/MCI_Inbox/
#
swagger.test.endpoints.enabled = true
########################################################

spring.application.admin.enabled=true
spring.boot.admin.client.enabled=true

# absolute path needed for a custom location,
# a path relative to the applications working dir can be used.
# Otherwise files are moved to a subdirectory
processing.dir.base.path = ${user.dir}

########################################################
#
# Sidora MCI Processing properties
#
# Default properties used to identify the Mci route logs
# edu.si.mci=edu.si.mci
#
########################################################

edu.si.mci=edu.si.mci


##########################################################################
#
# Default User pid/name to use when the mci folder holder does not have an account yet or they are not found
#
##########################################################################
#mci.default.owner.pid=si-user:62
#mci.default.owner.name=ngadia
mci.default.owner.pid=si-user:245
mci.default.owner.name=mcisqltest

##########################################################################
#
# Camel SQL Component Data Source configuration
#
##########################################################################
#Common Driver to use
si.mysql.db.driverClassName=com.mysql.cj.jdbc.Driver

# Drupal MySql database configuration for checking for valid users and getting there user pid
si.mysql.drupal.db.host=localhost
si.mysql.drupal.db.port=3307
si.mysql.drupal.db.name=fedora_wb
si.mysql.drupal.db.username=sidora
si.mysql.drupal.db.password=sidora
si.mysql.drupal.db.url=jdbc:mysql://${si.mysql.drupal.db.host}:${si.mysql.drupal.db.port}/${si.mysql.drupal.db.name}?zeroDateTimeBehavior=convertToNull&autoReconnect=true
si.mysql.drupal.db.validationQuery=select 1 as dbcp_connections_test
si.mysql.drupal.db.testOnBarrow=true
si.mysql.drupal.db.testWhileIdle=true

# Sidora MySql database for persisting incoming http requests
si.mysql.request.db.host=localhost
si.mysql.request.db.port=3307
si.mysql.request.db.name=sidora
si.mysql.request.db.username=sidora
si.mysql.request.db.password=sidora
si.mysql.request.db.url=jdbc:mysql://${si.mysql.request.db.host}:${si.mysql.request.db.port}/${si.mysql.request.db.name}?zeroDateTimeBehavior=convertToNull&autoReconnect=true
si.mysql.request.db.validationQuery=select 1 as dbcp_connections_test
si.mysql.request.db.testOnBarrow=true
si.mysql.request.db.testWhileIdle=true

##########################################################################
#
# Redelivery Policy for mci
# Note: For faster testing set the redeliveryDelay to 0
#
###########################################################################

# The following config retries for aprox 25min.
mci.redeliveryDelay=0
mci.maximumRedeliveries=10
mci.backOffMultiplier=2
mci.useExponentialBackOff=true
mci.retryAttemptedLogLevel=WARN
mci.retriesExhaustedLogLevel=ERROR
mci.logExhausted=true


#############################################################################
#
# URL used for Updating concepts tree nodes in workbench
#
#############################################################################

#workbench.host = http://si-oris-app07.si.edu
workbench.host = http://localhost:1818
camel.workbench.login.url = ${workbench.host}/user
camel.workbench.create.research.project.url = ${workbench.host}/sidora/ajax_parts/create_ps
camel.workbench.clear.cache.url = ${workbench.host}/sidora/pid_expired
camel.workbench.user = camelWBUser
camel.workbench.password = camelWBUser


#############################################################################
#
# Fedora Configs
#
#############################################################################

si.fedora.host=http://localhost:8181/fedora
si.fedora.user=fedoraAdmin
si.fedora.password=fedoraAdmin

# The fedora user must be different from the Camera Trap routes otherwise derivatives will not be made
si.fedora.batch.user=camelBatchProcess


#############################################################################
#
# Camera Trap Configs
#
#############################################################################

# For Camera Trap routes
si.ct.owner=forresterT
si.ct.namespace=ct
si.ct.root=si:121909


#############################################################################
#
# Fuseki Configs
#
#############################################################################

si.fuseki.endpoint = http://localhost:9080/fuseki/fedora3


#############################################################################
#
# FITS Configs
#
#############################################################################
fits.host = http://localhost:9180/fits


#############################################################################
#
# ExifTool Configs
#
#############################################################################

#exiftool.path=/usr/local/bin/exiftool
exiftool.path=/opt/sidora/fits/tools/exiftool/perl/exiftool