# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

####################################
# Generic Solr update requests
####################################
### Delete All using solr update endpoint
POST http://${host_url}:8090/solr/${sidora.solr.default.index}gsearch_solr_test/update
Content-Type: text/xml
<update><commit><delete><query>*:*</query></delete></commit></update>

### Delete All using solr update endpoint
POST http://${host_url}:8090/solr/${sidora.sianct.default.index}/update
Content-Type: text/xml

<update><commit><delete><query>*:*</query></delete></commit></update>

####################################
# Sidora Solr Camel Endpoint Calls
####################################
### Reindex All
GET http://${host_url}:8181/cxf/sidora/solr/reindex?gsearch_solr=true&gsearch_sianct=true&auth=${password}

### Delete ALL
GET http://${host_url}:8181/cxf/sidora/solr/deleteAll?gsearch_solr=true&gsearch_sianct=true&auth=${password}

### Delete By Query (Query with single PID)
GET http://${host_url}:8081/sidora/solr/deleteByQuery?gsearch_solr=true&gsearch_sianct=true&auth=${password}&query=PID:test.pid\:123

### Delete By Query (Query with PID and wildcard)
GET http://${host_url}:8081/sidora/solr/deleteByQuery?gsearch_solr=true&gsearch_sianct=true&auth=${password}&query=PID:PID:test.pid\:*
